/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author Alexandre Lima
 */
public class PainelPrincipal extends javax.swing.JFrame {
    
    Login login;

    /**
     * Creates new form PainelPrincipal
     */
    public PainelPrincipal() {
        initComponents();
//        login = new Login();
//        jdp.add(login);
//        login.setVisible(true);
//        login.setPosicao();
        CadAluno cadAluno = new CadAluno();
        jdp.add(cadAluno);
        cadAluno.setVisible(true);
        cadAluno.setPosicao();
        
        menuManage("deslogado");
    }
    
    public static void closeLogin(String perfil, String usuario, String senha) {
        System.out.println("Fechou login: Perfil: " + perfil + " - Usuario: " + usuario + " - Senha: " + senha);
    }
    
    private void menuManage(String profile) {
        switch (profile) {
            case "deslogado":
                menu_gerenciar_aluno.setEnabled(false);
                menu_alunos.setEnabled(false);
                menu_arquivo.setEnabled(false);
                menu_bancas.setEnabled(false);
                menu_informacao.setEnabled(false);
                menu_professores.setEnabled(false);
                menu_propostas.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_arquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_alunos = new javax.swing.JMenu();
        menu_gerenciar_aluno = new javax.swing.JMenuItem();
        menu_professores = new javax.swing.JMenu();
        menu_propostas = new javax.swing.JMenu();
        menu_bancas = new javax.swing.JMenu();
        menu_informacao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento dos TC do Curso SSI");

        jdp.setBackground(new java.awt.Color(204, 204, 255));
        jdp.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jdpComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jdpLayout = new javax.swing.GroupLayout(jdp);
        jdp.setLayout(jdpLayout);
        jdpLayout.setHorizontalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jdpLayout.setVerticalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        menu_arquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page.png"))); // NOI18N
        menu_arquivo.setText("Arquivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/door_in.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_arquivo.add(jMenuItem1);

        jMenuBar1.add(menu_arquivo);

        menu_alunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        menu_alunos.setText("Alunos");
        menu_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_alunosActionPerformed(evt);
            }
        });

        menu_gerenciar_aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/table_edit.png"))); // NOI18N
        menu_gerenciar_aluno.setText("Gerenciar");
        menu_gerenciar_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_gerenciar_alunoActionPerformed(evt);
            }
        });
        menu_alunos.add(menu_gerenciar_aluno);

        jMenuBar1.add(menu_alunos);

        menu_professores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/book_open.png"))); // NOI18N
        menu_professores.setText("Professores");
        jMenuBar1.add(menu_professores);

        menu_propostas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/table.png"))); // NOI18N
        menu_propostas.setText("Propostas");
        jMenuBar1.add(menu_propostas);

        menu_bancas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/group.png"))); // NOI18N
        menu_bancas.setText("Bancas");
        jMenuBar1.add(menu_bancas);

        menu_informacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/information.png"))); // NOI18N
        menu_informacao.setText("Informações");
        jMenuBar1.add(menu_informacao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_alunosActionPerformed
        
    }//GEN-LAST:event_menu_alunosActionPerformed

    /**
     * Método que captura ação do botão de gerenciar aluno
     */
    private void menu_gerenciar_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_gerenciar_alunoActionPerformed
        CadAluno telaAluno = new CadAluno();
        jdp.add(telaAluno);
        telaAluno.setVisible(true);
        telaAluno.setPosicao();
    }//GEN-LAST:event_menu_gerenciar_alunoActionPerformed

    private void jdpComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jdpComponentResized
        login.setPosicao();
    }//GEN-LAST:event_jdpComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdp;
    private javax.swing.JMenu menu_alunos;
    private javax.swing.JMenu menu_arquivo;
    private javax.swing.JMenu menu_bancas;
    private javax.swing.JMenuItem menu_gerenciar_aluno;
    private javax.swing.JMenu menu_informacao;
    private javax.swing.JMenu menu_professores;
    private javax.swing.JMenu menu_propostas;
    // End of variables declaration//GEN-END:variables
}
