/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lpii.view;

import br.com.lpii.model.Aluno;
import br.com.lpii.model.Professor;
import br.com.lpii.model.Utilitarios;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class FrmMenu extends javax.swing.JFrame {

    private Aluno aluno;
    private Professor professor;
    private String perfil;

    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public Professor getProfesso() {
        return professor;
    }

    public void setProfesso(Professor professo) {
        this.professor = professo;
    }

    public String getPerfil() {
        return perfil;
    }

    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        Utilitarios util = new Utilitarios();
        util.inserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/wallspaper.jpg"));
        Image image = icon.getImage();
        painel_desk = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g) {
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        label_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        label_matrícula = new javax.swing.JLabel();
        txt_matrícula = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_arquivo = new javax.swing.JMenu();
        submenu_trocarUsuario = new javax.swing.JMenuItem();
        submenu_sair = new javax.swing.JMenuItem();
        menu_aluno = new javax.swing.JMenu();
        submenu_prof_gerenciarAlunos = new javax.swing.JMenuItem();
        submenu_aluno_meuCadastro = new javax.swing.JMenuItem();
        menu_professor = new javax.swing.JMenu();
        submenu_prof_gerenciarProfessores = new javax.swing.JMenuItem();
        submenu_prof_areaInteresse = new javax.swing.JMenuItem();
        submentu_prof_cadastrarMinhasPropostas = new javax.swing.JMenuItem();
        menu_propostas = new javax.swing.JMenu();
        submenu_prof_gerenciarPropostas = new javax.swing.JMenuItem();
        submenu_aluno_escolherTema = new javax.swing.JMenuItem();
        submenu_prof_definirBanca = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento dos TC do Curso de SSI");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        label_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_usuario.setForeground(new java.awt.Color(0, 102, 51));
        label_usuario.setText("Usuário: ");

        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(0, 102, 0));
        txt_usuario.setText("Alexandre Lima");

        label_matrícula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_matrícula.setForeground(new java.awt.Color(0, 102, 51));
        label_matrícula.setText("Matrícula:");

        txt_matrícula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_matrícula.setForeground(new java.awt.Color(0, 102, 0));
        txt_matrícula.setText("Alexandre Lima");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_matrícula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_matrícula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario)
                .addContainerGap(577, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(label_matrícula)
                .addComponent(txt_matrícula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_usuario)
                .addComponent(txt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_desk.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel_deskLayout = new javax.swing.GroupLayout(painel_desk);
        painel_desk.setLayout(painel_deskLayout);
        painel_deskLayout.setHorizontalGroup(
            painel_deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel_deskLayout.setVerticalGroup(
            painel_deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_deskLayout.createSequentialGroup()
                .addGap(0, 479, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_arquivo.setForeground(new java.awt.Color(0, 102, 51));
        menu_arquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page.png"))); // NOI18N
        menu_arquivo.setText("Arquivo");
        menu_arquivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        submenu_trocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        submenu_trocarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_trocarUsuario.setForeground(new java.awt.Color(0, 102, 51));
        submenu_trocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arrow_refresh.png"))); // NOI18N
        submenu_trocarUsuario.setText("Trocar de usuário");
        submenu_trocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_trocarUsuarioActionPerformed(evt);
            }
        });
        menu_arquivo.add(submenu_trocarUsuario);

        submenu_sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        submenu_sair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_sair.setForeground(new java.awt.Color(0, 102, 51));
        submenu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_out.png"))); // NOI18N
        submenu_sair.setText("Sair");
        submenu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_sairActionPerformed(evt);
            }
        });
        menu_arquivo.add(submenu_sair);

        jMenuBar1.add(menu_arquivo);

        menu_aluno.setForeground(new java.awt.Color(0, 102, 51));
        menu_aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        menu_aluno.setText("Aluno");
        menu_aluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        submenu_prof_gerenciarAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        submenu_prof_gerenciarAlunos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_prof_gerenciarAlunos.setForeground(new java.awt.Color(0, 102, 51));
        submenu_prof_gerenciarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_edit.png"))); // NOI18N
        submenu_prof_gerenciarAlunos.setText("Gerenciar Alunos");
        submenu_prof_gerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_prof_gerenciarAlunosActionPerformed(evt);
            }
        });
        menu_aluno.add(submenu_prof_gerenciarAlunos);

        submenu_aluno_meuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        submenu_aluno_meuCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_aluno_meuCadastro.setForeground(new java.awt.Color(0, 102, 51));
        submenu_aluno_meuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_edit.png"))); // NOI18N
        submenu_aluno_meuCadastro.setText("Meu Cadastro");
        submenu_aluno_meuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_aluno_meuCadastroActionPerformed(evt);
            }
        });
        menu_aluno.add(submenu_aluno_meuCadastro);

        jMenuBar1.add(menu_aluno);

        menu_professor.setForeground(new java.awt.Color(0, 102, 51));
        menu_professor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        menu_professor.setText("Professor");
        menu_professor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        submenu_prof_gerenciarProfessores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        submenu_prof_gerenciarProfessores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_prof_gerenciarProfessores.setForeground(new java.awt.Color(0, 102, 51));
        submenu_prof_gerenciarProfessores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_edit.png"))); // NOI18N
        submenu_prof_gerenciarProfessores.setText("Gerenciar Professores");
        submenu_prof_gerenciarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_prof_gerenciarProfessoresActionPerformed(evt);
            }
        });
        menu_professor.add(submenu_prof_gerenciarProfessores);

        submenu_prof_areaInteresse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        submenu_prof_areaInteresse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_prof_areaInteresse.setForeground(new java.awt.Color(0, 102, 51));
        submenu_prof_areaInteresse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/text_list_bullets.png"))); // NOI18N
        submenu_prof_areaInteresse.setText("Selecionar Áreas de Interesse");
        submenu_prof_areaInteresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_prof_areaInteresseActionPerformed(evt);
            }
        });
        menu_professor.add(submenu_prof_areaInteresse);

        submentu_prof_cadastrarMinhasPropostas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        submentu_prof_cadastrarMinhasPropostas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submentu_prof_cadastrarMinhasPropostas.setForeground(new java.awt.Color(0, 102, 51));
        submentu_prof_cadastrarMinhasPropostas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        submentu_prof_cadastrarMinhasPropostas.setText("Cadastrar Minhas Propostas");
        submentu_prof_cadastrarMinhasPropostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submentu_prof_cadastrarMinhasPropostasActionPerformed(evt);
            }
        });
        menu_professor.add(submentu_prof_cadastrarMinhasPropostas);

        jMenuBar1.add(menu_professor);

        menu_propostas.setForeground(new java.awt.Color(0, 102, 51));
        menu_propostas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book.png"))); // NOI18N
        menu_propostas.setText("Propostas TCC");
        menu_propostas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        submenu_prof_gerenciarPropostas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        submenu_prof_gerenciarPropostas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_prof_gerenciarPropostas.setForeground(new java.awt.Color(0, 102, 51));
        submenu_prof_gerenciarPropostas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_open.png"))); // NOI18N
        submenu_prof_gerenciarPropostas.setText("Gerenciar Propostas");
        submenu_prof_gerenciarPropostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_prof_gerenciarPropostasActionPerformed(evt);
            }
        });
        menu_propostas.add(submenu_prof_gerenciarPropostas);

        submenu_aluno_escolherTema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        submenu_aluno_escolherTema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_aluno_escolherTema.setForeground(new java.awt.Color(0, 102, 51));
        submenu_aluno_escolherTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_open.png"))); // NOI18N
        submenu_aluno_escolherTema.setText("Escolher Tema");
        submenu_aluno_escolherTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_aluno_escolherTemaActionPerformed(evt);
            }
        });
        menu_propostas.add(submenu_aluno_escolherTema);

        submenu_prof_definirBanca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        submenu_prof_definirBanca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submenu_prof_definirBanca.setForeground(new java.awt.Color(0, 102, 51));
        submenu_prof_definirBanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        submenu_prof_definirBanca.setText("Definir Banca");
        submenu_prof_definirBanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_prof_definirBancaActionPerformed(evt);
            }
        });
        menu_propostas.add(submenu_prof_definirBanca);

        jMenuBar1.add(menu_propostas);

        jMenu1.setForeground(new java.awt.Color(0, 102, 51));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/help.png"))); // NOI18N
        jMenu1.setText("Ajuda");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_white_acrobat.png"))); // NOI18N
        jMenuItem1.setText("Manual");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_desk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_desk)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setExtendedState(this.MAXIMIZED_BOTH);

        if (getPerfil().equals("Aluno")) {
            txt_usuario.setText(aluno.getNome());
            label_usuario.setText("Aluno(a):");
            txt_matrícula.setText(String.valueOf(aluno.getMatricula()));
            label_matrícula.setText("Matrícula:");
        } else if (getPerfil().equals("Professor")) {
            txt_usuario.setText(professor.getNome());
            label_usuario.setText("Professor(a):");
            txt_matrícula.setText(String.valueOf(professor.getCodigo()));
            label_matrícula.setText("ID:");
        }

        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void submenu_trocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_trocarUsuarioActionPerformed
        // Métrodo para trocar de usuário fecha a tela de menu para realizar novo login
        FrmLogin telaLogin = new FrmLogin();
        this.dispose();
        telaLogin.setVisible(true);

    }//GEN-LAST:event_submenu_trocarUsuarioActionPerformed

    private void submenu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_sairActionPerformed
        // declara uma variável do tipo int
        int op;
        // pega o returno do JOptionPane para confirmar que usuário deseja sair
        op = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja sai?");
        // Se valor de op for 0 (zero) programa será fechado, pois usuário clicou em sim.
        if (op == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_submenu_sairActionPerformed

    private void submenu_prof_gerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_prof_gerenciarAlunosActionPerformed
        FrmAluno tela = new FrmAluno();
        tela.setVisible(true);
    }//GEN-LAST:event_submenu_prof_gerenciarAlunosActionPerformed

    private void submenu_prof_gerenciarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_prof_gerenciarProfessoresActionPerformed
        FrmProfessores tela = new FrmProfessores();
        tela.setVisible(true);
    }//GEN-LAST:event_submenu_prof_gerenciarProfessoresActionPerformed

    private void submenu_prof_areaInteresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_prof_areaInteresseActionPerformed
        FrmAreaInteresse tela = new FrmAreaInteresse();
        tela.setVisible(true);
        tela.setProfessor(professor);
    }//GEN-LAST:event_submenu_prof_areaInteresseActionPerformed

    private void submentu_prof_cadastrarMinhasPropostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submentu_prof_cadastrarMinhasPropostasActionPerformed
        FrmMinhasPropostas tela = new FrmMinhasPropostas();
        tela.setProfessor(professor);
        tela.setVisible(true);

    }//GEN-LAST:event_submentu_prof_cadastrarMinhasPropostasActionPerformed

    private void submenu_prof_gerenciarPropostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_prof_gerenciarPropostasActionPerformed
        // Abre formulário para gerenciamento de propostas para o TC
        FrmGerenciarPropostas tela = new FrmGerenciarPropostas();
        tela.setProfessor(professor);
        tela.setVisible(true);
    }//GEN-LAST:event_submenu_prof_gerenciarPropostasActionPerformed

    private void submenu_aluno_meuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_aluno_meuCadastroActionPerformed
        
        FrmMeuCadastroAluno tela = new FrmMeuCadastroAluno();
        tela.setAluno(aluno);
        tela.setVisible(true);
        
    }//GEN-LAST:event_submenu_aluno_meuCadastroActionPerformed

    private void submenu_aluno_escolherTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_aluno_escolherTemaActionPerformed
        // Abre JFrame para aluno escolher tema
        FrmEscolherTema tela = new FrmEscolherTema();
        tela.setAluno(aluno);
        tela.setVisible(true);
    }//GEN-LAST:event_submenu_aluno_escolherTemaActionPerformed

    private void submenu_prof_definirBancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_prof_definirBancaActionPerformed
        // Abre tela para definir banca
        FrmDefinirBanca telaDB = new FrmDefinirBanca();
        telaDB.setProfessor(professor);
        telaDB.setVisible(true);
    }//GEN-LAST:event_submenu_prof_definirBancaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Método para abrir o manual do programa
        String caminho = "src/manual.pdf";
        File arquivo = new File(caminho);
        try {
            Desktop.getDesktop().open(arquivo);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex,  "ERRO",JOptionPane.ERROR_MESSAGE);
 
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_matrícula;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JMenu menu_aluno;
    private javax.swing.JMenu menu_arquivo;
    public javax.swing.JMenu menu_professor;
    private javax.swing.JMenu menu_propostas;
    private javax.swing.JDesktopPane painel_desk;
    private javax.swing.JMenuItem submentu_prof_cadastrarMinhasPropostas;
    public javax.swing.JMenuItem submenu_aluno_escolherTema;
    public javax.swing.JMenuItem submenu_aluno_meuCadastro;
    private javax.swing.JMenuItem submenu_prof_areaInteresse;
    public javax.swing.JMenuItem submenu_prof_definirBanca;
    public javax.swing.JMenuItem submenu_prof_gerenciarAlunos;
    private javax.swing.JMenuItem submenu_prof_gerenciarProfessores;
    public javax.swing.JMenuItem submenu_prof_gerenciarPropostas;
    private javax.swing.JMenuItem submenu_sair;
    private javax.swing.JMenuItem submenu_trocarUsuario;
    private javax.swing.JLabel txt_matrícula;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
